inherit: true

build:
  nodes:
    tests:
      tests:
        override:
          - true # To disable Scrutinizer's own CI.
    analysis:
      tests:
        override:
          - 
              command: php-scrutinizer-run --enable-security-analysis
              on_node: 1
          -
              command: phpcs-run
              use_website_config: true
              on_node: 2

tools:
    php_code_sniffer: true
    php_cpd: false
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
    external_code_coverage: true
filter:
    excluded_paths:
        - lib/*
        - tests/*
        - includes/SiteConfiguration.php

build_failure_conditions:
    - 'elements.rating(<= F).new.exists'
    - 'issues.severity(>= MAJOR).new.exists'
