language: php

php:
  - 7.3
  
jobs:
  allow_failures:
    - php: 7.3

os:
  - linux

dist:
  - xenial

before_install:
  - pip install --user codecov

after_success:
  - codecov

git:
  submodules: true

before_script:
  - cd sql
  - bash test_db.sh 1
  - cd ..

script:
  - bash .travis.phplint.sh
  - phpunit --coverage-clover=coverage.xml
  - codecov

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikipedia-en-accounts-devs"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
