language: php

php:
  - 7.3

addons:
  mariadb: '10.1'

os: linux
dist: bionic

before_install:
  - composer install
  - pip install --user codecov

after_success:
  - codecov

git:
  submodules: true

before_script:
  - pecl install runkit7-alpha
  - phpenv config-add .travis.php.ini
  - cd sql
  - bash test_db.sh 1 localhost test_db root
  - cd ..

script:
  - bash .travis.phplint.sh
  - phpunit --verbose --coverage-clover=coverage.xml
  - codecov

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikipedia-en-accounts-devs"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
